### ISSUE TITLE
afterAll scenario execution

### ISSUE THREAD

**Issue by johnsickels** [flocasts/flagpole#35] opened 2020-05-07 20:22 UTC
Expected behavior is to execute a scenario afterAll other scenarios have completed. 

```
import flagpole from "flagpole";

const suite = flagpole("Execute a scenario after all other scenarios").afterAll(() => {
  scenarioB.execute();
});

const scenarioA = suite
  .scenario("Look at cars", "browser")
  .open("https://www.cars.com")
  .next(async (context) => {
    await context.exists("body");
  });

const scenarioB = suite
  .scenario("Look at boats", "browser")
  .wait()
  .open("https://www.boats.com")
  .next(async (context) => {
    await context.exists("body");
  });
```

Actual behavior:

The suite never completes. If ran headed, you can see scenarioA never finishes. 

What I've tried:

- The afterAll is successfully called when a simple console.log("hello world") takes the place of the scenario execution.
- scenarioB is successfully called when `scenarioB.execute()` is called from within scenarioA

Version:
- flagpole 2.3.8
- node 12.13.1
- typescript 3.7.2

**Comment by jasonbyrne** [comment] 2020-05-11 02:49
We'll have to talk about this more. This would never work by design. `afterAll` is never going to fire until ALL scenarios are done. And `afterAll` will only ever fire ONCE. This code is against the intended behavior so I'm going to close it.

**Closed by jasonbyrne** 2020-05-11 02:49 UTC
Labels: bug
